site_name: Open MiRoREA Project
repo_url: https://github.com/Open-MiRoREA
docs_dir: src
site_dir: docs
theme:
  name: material
  language: ja
  icon:
    logo: material/excavator
  features:
    - navigation.tabs         # 上部にタブ型メニュー
    - navigation.expand       # 左ナビゲーションのセクションを自動展開
    - navigation.top          # 「トップへ戻る」を表示
    - navigation.footer       # ページ下部に「前 / 次ページ」を表示
    - toc.integrate           # 左ナビゲーションに目次を統合
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - attr_list                 # Markdown要素に属性追加（図のレイアウト用）
  - admonition                # 注意・警告などのブロック (!!! note / warning)
  - pymdownx.details          # 折りたたみブロック (??? note)
  - pymdownx.superfences      # コードブロックの拡張（タブやネスト対応）
  - md_in_html                # HTMLブロック内でもMarkdownを有効にする（トップページのロボットのカード用）
nav:
  - Home: index.md
  - About: about.md
  - MiRoREA Excavator:
    - MiRoREA Excavatorの概要: mirorea_excavator/index.md
    - システム構成: mirorea_excavator/architecture.md
    - ハードウェアの作り方:
      - ハードウェアの作り方の概要: mirorea_excavator/hardware/index.md
      - Step 0 準備と部品: mirorea_excavator/hardware/prep_parts.md
      - Step 1 3Dプリント部品の造形: mirorea_excavator/hardware/3dprinting.md
      - Step 2 ベースラジコンの分解: mirorea_excavator/hardware/disassem.md
      - Step 3 はんだ付けとケーブルの製作: mirorea_excavator/hardware/solder_cables.md
      - Step 4 ポテンショメータの取り付け: mirorea_excavator/hardware/potentio.md
      - Step 5 旋回角推定センサの取り付け: mirorea_excavator/hardware/swing.md
      - Step 6 配線と組立て: mirorea_excavator/hardware/wiring_assem.md
    
    # - ソフトウェアのセットアップ:
    #   - 概要: mirorea_excavator/software/index.md
    #   - 準備とデータ: mirorea_excavator/software/prep_data.md
  - MiRoREA Dump Truck:
    - MiRoREA Dump Truckの概要: mirorea_dump_truck/index.md
copyright: © 2025 Ryosuke Yajima, Open MiRoREA Project