site_name: Open MiRoREA Project
repo_url: https://github.com/Open-MiRoREA
docs_dir: src
site_dir: docs
theme:
  name: material
  language: ja
  icon:
    logo: material/excavator
  features:
    - navigation.tabs          # 上部にタブ型メニュー
    - navigation.expand
    - navigation.footer
    - toc.integrate
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - md_in_html
nav:
  - Home: index.md
  - About: about.md
  - MiRoREA Excavator:
    - MiRoREA Excavatorの概要: mirorea_excavator/index.md
    # - システム構成: mirorea_excavator/architecture.md
    - ハードウェアのセットアップ:
      - ハードウェアのセットアップの概要: mirorea_excavator/hardware/index.md
      # - Step 0 準備と部品: mirorea_excavator/hardware/prep_parts.md
    #   - Step 1 3Dプリント部品の造形: mirorea_excavator/hardware/3dprinting.md
    #   - Step 2 はんだ付けとケーブルの製作: mirorea_excavator/hardware/solder_cables.md
    #   - Step 3 ラジコンの分解: mirorea_excavator/hardware/disassembly.md
    #   - Step 4 組み立て: mirorea_excavator/hardware/assembly.md
    #   - Step 5 配線: mirorea_excavator/hardware/wiring.md
    # - ソフトウェアのセットアップ:
    #   - 概要: mirorea_excavator/software/index.md
    #   - 準備とデータ: mirorea_excavator/software/prep_data.md
  - MiRoREA Dump Truck:
    - MiRoREA Dump Truckの概要: mirorea_dump_truck/index.md
copyright: © 2025 Ryosuke Yajima, Open MiRoREA Project